### ISSUE TITLE
Documentation & Examples

### ISSUE THREAD

**Issue by Narretz** [cypress-io/packherd#5]
I found this project form the PR in cypress https://github.com/cypress-io/cypress/pull/18331

It does sound quite interesting as a ts-node replacement, but there is no readme (with possible limitations / planned features) and no docs / examples. I would be more likely to try it out if there was more information available.

**Comment by thlorenz** [comment]
Yeah I had not bandwidth so far to add docs. I'm still working out kinks and will add docs once that is complete.
For now you can look inside `packages/ts` to on that PR to see how it can be used.
